package com.geopokrovskiy.javacore.chapter10;

public class SuperSubCatch {
   /* public static void main(String[] args) {
        try{
            int a = 0;
            int b = 42 / a;
        } catch (Exception e){
            System.out.println("Catch of general Exception class.");
        } catch (ArithmeticException e){ // Error : the super-exception has already been caught!
            System.out.println("Inaccessible code!");
        }
    }*/
}
